name: "mnist_pt"
backend: "pytorch"
max_batch_size: 128
dynamic_batching { }

input [
  {
    name: "input0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 1, 28, 28 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]