model_name: hifigan
model_path: hifigan.pt
model_repository: navigator_model_repository
inputs:
  INPUT__0:
    name: INPUT__0
    shape:
    - -1
    - 80
    - -1
    dtype: float32
outputs:
  OUTPUT__0:
    name: OUTPUT__0
    shape:
    - -1
    - 1
    - -1
    dtype: float32
min_shapes:
  INPUT__0:
  - 1
  - 80
  - 40
opt_shapes:
  INPUT__0:
  - 8
  - 80
  - 140
max_shapes:
  INPUT__0:
  - 128
  - 80
  - 300
rtol:
  OUTPUT__0: 0.001
atol:
  OUTPUT__0: 0.04
value_ranges:
  INPUT__0:
  - 0.0
  - 1.0
max_workspace_size: 14000000000
