# SPDX-FileCopyrightText: 2021 NVIDIA CORPORATION
# SPDX-License-Identifier: MIT

model_repository: model_repository
# One must specify the full path to the output_model_repository here:
output_model_repository_path: /raid/users/dmitrym/triton_model_analyzer/output_model_repository
triton_launch_mode: docker
override_output_model_repository: True
# These are different between manual and auto
run_config_search_disable: False
run_config_search_max_concurrency: 16 

profile_models:
  hifigan:
    perf_analyzer_flags:
      shape: "spec:80,140"


analysis_models: hifigan
 


